appenders:
  stdout:
    kind: console
  binance_raw:
    kind: file
    path: /home/ubuntu/rust_bin_bot/logs/reload_params.log
    encoder:
      pattern:  "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
root:
  level: info
  appenders:
    - binance_raw
    - stdout
